baseurl = "https://www.fluxengine.dev/"
title = "FluxLog"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
# [services.disqus]
# shortname = "0zminDev"

# Giscus Comments
[params.giscus]
  repo = "0zminDev/FluxLog"
  repoID = "R_kgDONJK7lg"  # You need to replace this with your actual repo ID
  category = "General"     # You need to replace this with your discussion category
  categoryID = "DIC_kwDONJK7ls4CjpnF"  # You need to replace this with your actual category ID
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "en"
  loading = "lazy"

[markup.highlight]
style = "github-dark"

[params]
  author = "0zminDev"
  info = "FluxEngine - A simple game engine written in C++ and Vulkan"
  description = "FluxEngine - A simple game engine written in C++ and Vulkan"
  keywords = "blog,game-engine"
  avatarurl = "images/avatar.png"

  faviconSVG = "/images/favicon.svg"
  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  since = 2025

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/0zminDev/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'